(deftheme jnk-monokai-white
  "Created 2020-05-03.")

(custom-theme-set-faces
 'jnk-monokai-white
 '(default ((t (:family "Courier" :foundry "nil" :width normal :height 140 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#0A0A0A" :background "white" :stipple nil :inherit nil))))
 '(cursor ((t (:inverse-video t :foreground "#E4E1E3" :background "#0A0A0A"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#878473"))))
 '(org-todo ((t (:foreground "#ff0000"))))
 '(org-done ((t (:foreground "#00ff00"))))
 '(line-number ((t (:foreground "#0099cc"))))
 '(line-number-current-line ((t (:foreground "#0099cc"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#5FD7FF"))))
 '(highlight ((t (:background "#C0C0C0"))))
 '(region ((t (:background "#C0C0C0" :inherit (highlight)))))
 '(shadow ((t (:foreground "#878473"))))
 '(secondary-selection ((t (:background "#C0C0C0" :inherit (region)))))
 '(trailing-whitespace ((t (:background "#EB007D"))))
 '(font-lock-builtin-face ((t (:weight normal :foreground "#EB007D"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#878473"))))
 '(font-lock-comment-face ((t (:foreground "#878473"))))
 '(font-lock-constant-face ((t (:foreground "#29007a"))))
 '(font-lock-doc-face ((t (:foreground "#8b8332"))))
 '(font-lock-function-name-face ((t (:foreground "#78b800"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#EB007D"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#8b8332"))))
 '(font-lock-preprocessor-face ((t (:foreground "#EB007D"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :foreground "#29007a"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :foreground "#8b8332"))))
 '(font-lock-string-face ((t (:foreground "#8b8332"))))
 '(font-lock-type-face ((t (:slant normal :foreground "#0099cc"))))
 '(font-lock-variable-name-face ((t (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((t (:weight bold :slant italic :underline (:color foreground-color :style line) :foreground "#FF8C00"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#0099cc"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#29007a"))))
 '(fringe ((t (:foreground "#1B1E1C" :background "#F5F5F5"))))
 '(header-line ((t (:box (:line-width 1 :color "#3D3D3D" :style unspecified) :foreground "#FFFAFA" :background "#474747"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width 1 :color "#474747" :style unspecified) :foreground "#F5F5F5" :background "#1B1E1C"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#78b800"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#3D3D3D" :style unspecified) :foreground "#878473" :background "#1B1E1C"))))
 '(isearch ((t (:foreground "#1B1E1C" :background "#8b8332" :inherit (region)))))
 '(isearch-fail ((t (:weight bold :foreground "#EB007D" :background "#1B1E1C" :inherit (isearch)))))
 '(lazy-highlight ((t (:background "#C0C0C0" :inherit (highlight)))))
 '(match ((t (:weight bold :foreground "#1B1E1C" :background "#78b800"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'jnk-monokai-white)
