(deftheme jnk-monokai-black
  "Created 2020-05-02.")

(custom-theme-set-faces
 'jnk-monokai-black
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "#F5F5F5" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "default" :family "Monospace"))))
 '(cursor ((t (:inverse-video t :foreground "#1B1E1C" :background "#F5F5F5"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#8B8878"))))
 '(org-todo ((t (:foreground "#ff0000"))))
 '(org-done ((t (:foreground "#00ff00"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#5FD7FF"))))
 '(highlight ((t (:background "#474747"))))
 '(region ((t (:background "#474747" :inherit (highlight)))))
 '(shadow ((t (:foreground "#8B8878"))))
 '(secondary-selection ((t (:background "#3E3E3E" :inherit (region)))))
 '(trailing-whitespace ((t (:background "#FF1493"))))
 '(font-lock-builtin-face ((t (:weight normal :foreground "#FF1493"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#8B8878"))))
 '(font-lock-comment-face ((t (:foreground "#8B8878"))))
 '(font-lock-constant-face ((t (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((t (:foreground "#CDC673"))))
 '(font-lock-function-name-face ((t (:foreground "#87D700"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#FF1493"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#CDC673"))))
 '(font-lock-preprocessor-face ((t (:foreground "#FF1493"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :foreground "#AF87FF"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :foreground "#CDC673"))))
 '(font-lock-string-face ((t (:foreground "#CDC673"))))
 '(font-lock-type-face ((t (:slant normal :foreground "#5FD7FF"))))
 '(font-lock-variable-name-face ((t (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((t (:weight bold :slant italic :underline (:color foreground-color :style line) :foreground "#FF8C00"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#5FD7FF"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#AF87FF"))))
 '(fringe ((t (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(header-line ((t (:box (:line-width 1 :color "#3D3D3D" :style unspecified) :foreground "#FFFAFA" :background "#474747"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width 1 :color "#474747" :style unspecified) :foreground "#F5F5F5" :background "#1B1E1C"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#87D700"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#3D3D3D" :style unspecified) :foreground "#8B8878" :background "#1B1E1C"))))
 '(isearch ((t (:foreground "#1B1E1C" :background "#CDC673" :inherit (region)))))
 '(isearch-fail ((t (:weight bold :foreground "#FF1493" :background "#1B1E1C" :inherit (isearch)))))
 '(lazy-highlight ((t (:background "#3E3E3E" :inherit (highlight)))))
 '(match ((t (:weight bold :foreground "#1B1E1C" :background "#87D700"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'jnk-monokai-black)
